name: Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    test:
      runs-on: ubuntu-latest
      services:
        selenium:
          image: selenium/standalone-chrome
          ports:
            - 4444:4444
          options: >-
            --shm-size=2g
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.9'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run Selenium tests
          run: |
            pytest tests/selenium_tests.py --driver Remote --remote-url http://localhost:4444/wd/hub